messages:
   - '&eWelcome to the &4DG&8+&3MG&8 Club&e!'
   - '&eJoin our forum community at &dDG-MG.club&e today!'
   - '&eLooking for factions survival? Join &dMinegus&e!'
   - '&eNeed an invite for &6Seasons&e? Request one on our forum!'
   - '&eZombie survival? Try out &2Wasteland&e!'
   - '&eFeeling creative? Visit our &aPlots &eserver!'
   - '&5Minigames&e are coming soon!'